### ISSUE TITLE
Any Good Starting Issues?

### ISSUE THREAD

**Issue by thomasmost** [akula-bft/akula#127]
I would love to get involved as an open source contributor. Any advice on where to start? And does anyone have the bandwidth to make a list of possible tasks/areas of improvement?

I'm a neophyte Rust dev, but learning quickly! Thanks!

**Comment by vorot93** [comment]
Thanks for your interest! What do you want to see next in Akula? It's generally best to work on what's closest to your heart's liking.

**Comment by thomasmost** [comment]
I guess I've been thinking a lot about client diversity in Ethereum—I know there are many elements still missing for this to replace Geth, but that's the goal I'd like to drive towards

**Comment by vorot93** [comment]
Added to README in https://github.com/akula-bft/akula/commit/424cd7ecacfb846fcaada863afb64b3cf8e35f3c.
