### ISSUE TITLE
Error in production build 

### ISSUE THREAD

**Issue by enmohsinali** [akula-bft/akula#167]
error: failed to run custom build command for `ethnum-intrinsics v1.0.1 (https://github.com/vorot93/ethnum-rs?branch=staging#4ee19fe9)`

**Comment by vorot93** [comment]
Do you have Clang installed?

**Comment by PeaStew** [comment]
Which version of Clang?

**Comment by PeaStew** [comment]
> error: failed to run custom build command for `ethnum-intrinsics v1.0.1 (https://github.com/vorot93/ethnum-rs?branch=staging#4ee19fe9)`

need to install clang-12 and possibly also change/create /usr/lib/clang -> /usr/lib/clang-12

**Comment by vorot93** [comment]
Updated README
