### ISSUE TITLE
Implement database versioning and migration infra

### ISSUE THREAD

**Issue by vorot93** [akula-bft/akula#172]
Users should be able to safely upgrade old database when they launch newer versions of Akula. For this we need to implement versioning and support for running migrations.

**Comment by 0xKitsune** [comment]
Hello, I was looking through the issues for a good first issue and came across this one. Can you provide any pointers as to what in the codebase needs to be done for this?

**Comment by vorot93** [comment]
- Implement versioning system, most likely as a `const DB_VERSION: usize` that is also written into database.
- If `DB_VERSION > db.version`, then run migrations that return new version: `fn my_migration(db: MdbxEnvironment) -> anyhow::Result<usize>`.
- Keep running migrations until `DB_VERSION == db.version`
- If `DB_VERSION` is too far along for migrations, then DB is too old and we should exit, asking user to resync.

**Comment by 0xJepsen** [comment]
> Hello, I was looking through the issues for a good first issue and came across this one. Can you provide any pointers as to what in the codebase needs to be done for this?

Hey Kitsune, are you still working on this? I wouldn't want to front you here but also looking to get my hands dirty with this client.
