### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by byhashdong** [akula-bft/akula#184]
```
error: failed to run custom build command for `ethnum-intrinsics v1.0.1 (https://github.com/vorot93/ethnum-rs?branch=staging#4ee19fe9)`
```
ps: clang-10 already installed

**Comment by PeaStew** [comment]
Same error

**Comment by PeaStew** [comment]
> ```
> error: failed to run custom build command for `ethnum-intrinsics v1.0.1 (https://github.com/vorot93/ethnum-rs?branch=staging#4ee19fe9)`
> ```
> 
> ps: clang-10 already installed

need to install clang-12 and possibly also change/create /usr/lib/clang -> /usr/lib/clang-12

**Comment by vorot93** [comment]
Updated README
