### ISSUE TITLE
build error in win10

### ISSUE THREAD

**Issue by yyjia** [akula-bft/akula#197]
problem when compiling on windows
![WechatIMG511](https://user-images.githubusercontent.com/21003542/172275696-11180234-6ebc-42e8-9aec-610b46ef4eeb.png)

**Comment by banyudu** [comment]
>As the error message states, you cannot compile that code with stable Rust. You need to install nightly Rust and then use it to compile the program:

```bash
rustup install nightly
cargo +nightly install racer
```

Reference: https://stackoverflow.com/questions/53136717/errore0554-feature-may-not-be-used-on-the-stable-release-channel-couldnt
