### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by EvanVanNessEth** [akula-bft/akula#219]
"failed to select a version for the requirement 'serde_with = "^2"'

candidate versions found which didn't match 1.14, 1.13, 1.12.1

**Comment by vorot93** [comment]
This is extremely strange as serde_with 2.0.0 is published on crates.io

https://crates.io/crates/serde_with

Could you please delete `~/.cargo/git` and `~/.cargo/registry` just in case?

**Comment by EvanVanNessEth** [comment]
i'll try again this week, will likely just spin up a fresh VM to give it a shot.

**Comment by LinuXperia** [comment]
I had the same problem with Ubuntu 20.04.
After a full new install of the newest  Ubuntu 22.04 version i could surpass 
"failed to select a version for the requirement 'serde_with = "^2"'
the fail building problem.

So all what is needed is to use newest Ubuntu 22.04 and follow the build instruction steps.

On the website
https://akula.app/installation.html
there are two small syntax error:

First Syntax Error is:
> prototobuf-compiler
should be corrected to
> protobuf-compiler

Second Syntax Error is:
> sudo apt install {libprotobuf-dev,libprotobuf-lite31,libprotoc31,libprotobuf31,protobuf-compiler}_3.20.1-1_amd64.deb
should be corrected to
> sudo dpkg -i {libprotobuf-dev,libprotobuf-lite31,libprotoc31,libprotobuf31,protobuf-compiler}_3.20.1-1_amd64.deb

libprotobuf-dev requires as dependecie also zlib1g-dev and becouse of this a additional package is required to be installed like this before

> sudo apt install zlib1g-dev

I had also on a total fresh new Ubuntu 22.04 System to install aditional pkg-config
also as akula fails to build the dependencie "e2p-sys" with this error message here
> error: failed to run custom build command for `e2p-sys v0.1.0 (https://github.com/michaellass/e2p-sys.git#b9970006)

> sudo apt instal pkg-config

After a fresh Ubuntu 22.04 install,
addiding this two packages after this

> sudo apt instal pkg-config zlib1g-dev

and following the build instruction steps on the website i was able to compile and run
akula.

> 
> Building [=======================> ] 520/521: akula(bin)                                                                                                                                              
> Finished production [optimized] target(s) in 8m 26s
> 
> ./target/production/akula --help
> Akula 
> Next-generation Ethereum implementation.
> 

So this Issue can be closed as solved.

**Comment by vorot93** [comment]
Instructions updated, thanks!
