### ISSUE TITLE
Dockerfile should use Fedora as base

### ISSUE THREAD

**Issue by vorot93** [akula-bft/akula#243]
Ubuntu ships old protobuf requiring weird hacks like installing packages from Debian experimental.

See [this](https://github.com/wmitsuda/one-liner-archive/blob/main/sepolia-akula-lighthouse/Dockerfile) example.

**Comment by Genysys** [comment]
Can I pick this up?

**Comment by vorot93** [comment]
@Genysys Sure! Just fork the repo, implement this and submit a PR.
