### ISSUE TITLE
Reliably bind to/discover public IP

### ISSUE THREAD

**Issue by vorot93** [akula-bft/akula#244]
Currently we [use UPnP to detect public IP address](https://github.com/akula-bft/akula/blob/0db1d21b3451e71df2f7a66043f21b74498dad85/src/sentry/devp2p/disc/v4/node.rs#L233). However, it's only good if we are behind a UPnP-enabled gateway like most home routers. In other cases, we may have issues with P2P discovery.

Need to evaluate [public-ip](https://github.com/avitex/rust-public-ip) crate and replace current UPnP mechanism if it brings benefit.

**Comment by Genysys** [comment]
I would love to pick this up

**Comment by vorot93** [comment]
@Genysys feel free to submit a PR
