### ISSUE TITLE
Limit exposed RPC APIs with a command line flag

### ISSUE THREAD

**Issue by vorot93** [akula-bft/akula#258]
APIs are already dynamically activated [here](https://github.com/akula-bft/akula/blob/master/bin/akula.rs#L224), just need to predicate this process on CLI flag.

**Comment by 0xKitsune** [comment]
I would be happy to pick this one up and can jump on it tonight. Are you thinking command line arguments for each api implementation like this?

```rust

    /// Enable the net API
    #[clap(long)]
    pub net_api: bool,

    /// Enable the Erigon API
    #[clap(long)]
    pub erigon_api: bool,

    /// Enable the Otterscan API
    #[clap(long)]
    pub otterscan_api: bool,

    /// Enable the Trace API
    #[clap(long)]
    pub trace_api: bool,

    /// Enable the Web3 API
    #[clap(long)]
    pub web3_api: bool,
    
```

Do you want an option to include all API with one flag in addition to the individual flags?

```rust
    /// Enable all available APIs through RPC
    #[clap(long)]
    pub enable_all_apis: bool
```


Let me know if you had a different direction in mind.

**Comment by LinuXperia** [comment]
My Understanding is that we need to limit access to the exposed RPC APIs
like bitcoin or ethereum are doing this.

https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.setup-bitcoind-connection.html#bitcoin-node-settings

> ./bitcoind
> --rpcallowip=0.0.0.0/0
> --rpcuser=bitcoin
> --rpcpassword=J9JkYnPiXWqgRzg3vAA

Aka we need a user:password authentication possibility to limit access to the exposed apis.
another possibility is to use basic http authetntication with header
https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-password-based-authentication

I have done some look how this can be done even i am just starting to learn how to do rust programming but it looks like
best and easy solution is to use jsonrpsee authentication as akula use jsonrpsee for the rpc interface communication

https://github.com/akula-bft/akula/blob/master/bin/akula.rs#L22

https://docs.rs/http-auth-basic/latest/http_auth_basic/

**Comment by 0xKitsune** [comment]
Ahh ok, I was not familiar. I would be happy to tag team this if you want.

**Comment by LinuXperia** [comment]
@0xKitsune

Not sure what "tag team" means
but i would love to have the possibility to secure
exposed rpc apis like bitcoin node does it
using the cli flags  "--rpcuser" "--rpcpassword"
Its a security improvement that will make akula much popular as
it will prevent other people from abusing the a exposed akula node without permision.

**Comment by vorot93** [comment]
Implemented in master.
