### ISSUE TITLE
stuck "Awaiting chain tip" on Goerli

### ISSUE THREAD

**Issue by chaseadam** [akula-bft/akula#264]
I am exploring Akula with an attempt to sync Goerli chain, but appear to be stuck at ["Awaiting chain tip..."](https://github.com/akula-bft/akula/blob/1917f4cc3044a6f706aaf6ba12377810b2cb5ff1/src/stages/headers.rs#L100)

I only see periodic "INFO P2P node peer info:" with varying amounts of connections.

```
2022-08-28T13:27:41.444660Z  INFO Running staged sync
2022-08-28T13:27:41.445975Z  INFO { 1/14 Headers }: RUNNING from genesis
2022-08-28T13:27:41.446691Z  INFO { 1/14 Headers }: Awaiting chain tip...
2022-08-28T13:27:46.446373Z  INFO P2P node peer info: 1 active (+0 dialing) / 100 max.
```

Attempts to sync mainnet progresses as expected, but I did note that it never appears to hit "Awaiting chain tip" message:

```
2022-08-28T13:34:34.108726Z  INFO { 1/14 Headers }: RUNNING from genesis
2022-08-28T13:34:39.108049Z  INFO P2P node peer info: 2 active (+20 dialing) / 100 max.
2022-08-28T13:34:42.360854Z  INFO { 1/14 Headers }: Target block for download: 90000
2022-08-28T13:34:42.360932Z  INFO { 1/14 Headers }: Download session 1 to 90000
```

The [ChainSpecs](https://github.com/akula-bft/akula/tree/5a1816a5d526ff087b902b64458920f5ffad4ed8/src/res/chainspec) are very different between Goerli and Mainnet, so it may be following a different code path. They were updated [12 days ago](https://github.com/akula-bft/akula/pull/235).

I thought a third party consensus beacon client may help inform Akula where tip was, but my attempts to use Lighthouse with Akula result in the following error:

```
Aug 28 13:56:03.653 ERRO Error updating deposit contract cache   error: "All fallbacks errored: http://127.0.0.1:8545/, auth=true => BlockDownloadFailed(\"eth_getBlockByNumber call failed ServerMessage { code: -32000, message: \\\"sync progress not found\\\" }\")", retry_millis: 60000, service: deposit_contract_rpc
...
Aug 28 13:56:18.007 ERRO Execution engine call failed            error: ServerMessage { code: -32601, message: "Method not found" }, service: exec
Aug 28 13:56:18.007 ERRO Unable to get transition config         error: Api { error: ServerMessage { code: -32601, message: "Method not found" } }, service: exec
Aug 28 13:56:18.007 ERRO Not ready for merge                     hint: try updating Lighthouse and/or the execution layer, info: Could not confirm the transition configuration with the execution endpoint: "EngineError(Api { error: ServerMessage { code: -32601, message: \"Method not found\" } })", service: slot_notifier
```

Has anyone successfully synced a "post-merge" chain (i.e. Goerli) recently? Any advice on where I went wrong or guidance on additional debugging?

**Comment by vorot93** [comment]
Most likely issue is that syncing CL is _slow_. This works for me:
```
cargo run --release --bin lighthouse -- beacon_node --network=goerli --execution-endpoints=http://localhost:8551 --execution-jwt=/home/user/.local/share/akula/jwt.hex --checkpoint-sync-url="https://goerli.checkpoint-sync.ethdevops.io" --purge-db
```

**Comment by chaseadam** [comment]
I had been using the incorrect port number to connect lighthouse (CL) to Akula. After I used the proper `--engine-listen-address` (default: 127.0.0.1:8551) with lighthouse, akula "woke up" and started syncing:

```
2022-08-29T10:32:04.328640Z  INFO { 1/14 Headers }: Received 1024 headers from peer 0/0x7865…c603
2022-08-29T10:32:04.333176Z  INFO { 1/14 Headers }: Buffered 2061312 (+1024) headers
2022-08-29T10:32:04.333364Z  INFO { 1/14 Headers }: Requesting 1024 headers ending at #5430190/0x679cc885fca445d442ca71790ce44c406bba3f0ab7c2dfae60de3
fbf177a6567
```

@vorot93's hint to use `--checkpoint-sync-url` (which I didn't know about before), was helpful to get my lighthouse synced quickly, though I am not sure if the checkpoint sync was required to address the akula "stuckness"

There are still errors in lighthouse related to `sync progress not found`, but it does not appear to block progress:

```
Aug 29 10:36:37.090 ERRO Error updating deposit contract cache   error: "All fallbacks errored: http://127.0.0.1:8852/, auth=true => BlockDownloadFailed(\"eth_getBlockByNumber call failed ServerMessage { code: -32000, message: \\\"sync progress not found\\\" }\")", retry_millis: 60000, service: deposit_contract_rpc
```
