### ISSUE TITLE
Please support parity_PubSub from OpenEthereum

### ISSUE THREAD

**Issue by ytrezq** [akula-bft/akula#276]
# Rationale

OpenEthereum is deprecated but the software using it aren’t. The [PubSub](https://openethereum.github.io/JSONRPC-parity_pubsub-module) module allow to turn any rpc methods into a watch method.

Beside compatibility, **extremely useful when the block is set to `pending`** in order to get the transaction to frontrun with `eth_getstorageat`.

I’m still using OpenEthereum on Gnosis Chain as a result.

# Implementation

No ideas on how to implement it.

**Comment by vorot93** [comment]
We do not indend to implement pubsub based on JSONRPC. Use our gRPC API instead.
