### ISSUE TITLE
Please support parity_listStorageKeys #47 

### ISSUE THREAD

**Issue by ytrezq** [akula-bft/akula#277]
# Rationale
[This api still](https://openethereum.github.io/JSONRPC-parity-module#parity_liststoragekeys) OpenEthereum only, allows to list all storage/blockchain on past blocks and is required to build a token rich list on past blocks as well required by many security analysis tools.

# Implementation
No idea on how to implement it though it looks like https://github.com/ledgerwatch/erigon failed to find a way to implement it without breaking database compatibility and thus is unwilling to implement it. Please notice OpenEthereum required the database to be fatdb enabled in addition to tracing enabled (full archive node instead of just archive node).

**This is the reason why I’m still using OpenEthereum for Gnosis**.

**Comment by vorot93** [comment]
You explained yourself why this isn't going to be implemented.

**Comment by ytrezq** [comment]
@vorot93 by breaking database compatibility I m meaning not possible to add a switch like `fatdb` at sync time? I m not talking about changing the database of existing implementations.

You do support `parity_trace` why not doing the same for supporting full archival nodes than just archival nodes?

**Comment by vorot93** [comment]
Please test the linked PR. Note that Akula does not yet support Gnosis Chain and other AuRa-based networks.

**Comment by ytrezq** [comment]
@vorot93 : then does Akula supports The Merge ?

**Comment by vorot93** [comment]
@ytrezq This question is [answered on our website](https://akula.app)

**Comment by ytrezq** [comment]
> This question is [answered on our website](https://akula.app)

@vorot93 : then how to use it ? Is Akula a consensus client on it’s own ? How to enable `parity_listStorageKeys` in your pr ?

**Comment by vorot93** [comment]
@ytrezq You connect beacon chain node to Akula same way you do with any other EL node. `parity_listStorageKeys` is enabled by default.

**Comment by ytrezq** [comment]
@vorot93 : does https://akula.app/rpc.html means Akula doesn’t supports getlogs and `eth_filter` related methods ?

**Comment by vorot93** [comment]
This page is related to the issue at hand, not a discussion or manual. You are welcome to ask in the Telegram chat instead.

**Comment by ytrezq** [comment]
@vorot93 : I can’t use your pr because https://github.com/vorot93/ethnum-rs?branch=impls#6a940856 use clang instead of $CC/gcc which isn’t available in a recent version enough for my platform.

It doesn’t build.

**Comment by vorot93** [comment]
Try on another platform then, clang 12+ is a must.
