### ISSUE TITLE
Unexpected variant named `Ethash`in enum `SealVerificationParams`

### ISSUE THREAD

**Issue by 0xevm1** [akula-bft/akula#307]
I just pulled from master branch and recompiled, starting akula again from the production folder now gives me an error and the program quits

```
./akula
INFO Starting Akula (akula/v0.1.0-master-1df8acf-2022-09-21)
Error: 1:53: Unexpected variant named `Ethash`in enum `SealVerificationParams`, expected either `Clique` or `Beacon` instead
```

**Comment by vorot93** [comment]
Please run
`cargo run --bin akula-toolbox -- --datadir=<akula mainnet datadir> overwrite-chainspec <akula source dir>/src/res/chainspec/ethereum.ron`

Or resync.
