### ISSUE TITLE
Switch to stable Rust

### ISSUE THREAD

**Issue by vorot93** [akula-bft/akula#87]
We had a good run with nightly, allowing us to (ab)use newest features of Rust. Unfortunately, all good things come to end, and we have to go back to stable now.

The hardest are [KV-Transaction-Cursor traits](https://github.com/akula-bft/akula/blob/master/src/kv/traits.rs#L11). Here we use GATs to represent lifetime hierarchy between the three.

Other than that, the rest of feature flags are easy to git rid of.

**Comment by blasrodri** [comment]
> We had a good run with nightly, allowing us to (ab)use newest features of Rust. Unfortunately, all good things come to end, and we have to go back to stable now.
> 
> The hardest are [KV-Transaction-Cursor traits](https://github.com/akula-bft/akula/blob/master/src/kv/traits.rs#L11). Here we use GATs to represent lifetime hierarchy between the three.
> 
> Other than that, the rest of feature flags are easy to git rid of.

I can help out with this, if you want. Doesn't `evmodin` have nightly features as well? (namely in `interrupt.rs`)

**Comment by vorot93** [comment]
We have removed KV traits, but do retain the use of generators for now. Until we see real demand for Akula on stable, using nightly gives us tangible performance benefits.
